### ISSUE TITLE
Watr username

### ISSUE THREAD

**Issue by niall-watr** [watr/dotfiles#1]
Hi @watr , we are creating a github organisation for www.watr.org, our foundation supporting development of our blockchain protocol. We would love to be able to use the name Watr for our org, but it appears you have been using that for some time. I was wondering if you would be willing to discuss giving up the username? Feel free to send me an email to niall@watr.org. Thanks

**Comment by niall-watr** [comment]
A gentle nudge on this, I would love to receive a response from you

**Comment by watr** [comment]
Hi @niall-watr,I like the name @watr and have some fond memories of it. I can't give it away.
Thank you

**Comment by niall-watr** [comment]
Thanks for responding, I appreciate you taking the time
